server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee
    username: root
    password: Perfect2001

  jpa:
    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      format-sql: true
      type: info
      use-sql-comments: true
      properties:
        hibernate.use_sql_comments: true
        hibernate.format_sql: true

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: zw.co.afrosoft

management:
  endpoint:
    health:
      show-details: ALWAYS
    endpoints:
      web:
        exposure:
          include: "*"

logging:
  level:
    org.springframework: INFO
    design.boilerplate.springboot: INFO

## FIXME : Customize JWT token and Swagger information for your application

jwt:
  secretKey: secret
  issuer: afrosoft.co.zw
  expirationMinute: 10

swagger:
  contact-name: Perfect Makuwerere
  contact-mail: perfect.makuwerere@afrosoft.co.zw
  contact-url:
  app-name: Hr Leave System
  app-description: "Spring Boot"
  app-version: 2.0.0
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0
